blog/urls.py
from django.urls import path
from .feeds import LatestEntriesFeed
from .views import (
    blog_view,
    blog_single,
    test_view,
    categories_view,
    blog_search,
    author_view,
)

app_name = "blog"

urlpatterns = [
    path("", blog_view, name="index"),
    path("<int:pid>", blog_single, name="single"),
    path("category/<str:cat_name>", blog_view, name="category"),
    path("categories", categories_view, name="categories"),
    path("tag/<str:tag_name>", blog_view, name="tag"),
    path("author/<str:author_username>", blog_view, name="author"),
    path("search/", blog_search, name="search"),
    path("author/", author_view, name="author"),
    path("test", test_view, name="test"),
    path("rss/feed", LatestEntriesFeed(), name="rss"),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

# development time imports
import debug_toolbar
from django.urls import path  
from website.views import maintenance 
# ------------------------

from django.conf import settings
from django.urls import re_path
# from django.conf.urls import handler404

handler404 = 'website.views.custom_404'

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}


urlpatterns = [
    path('maintenance/', maintenance, name='maintenance'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('website.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('robots.txt', include('robots.urls')),
    path("__debug__/", include(debug_toolbar.urls)),
    path('summer_note/', include('django_summernote.urls')),
    path(r'captcha/', include('captcha.urls')), 
    path('accounts/', include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from .views import about_view, contact_us_view, index_view, newsletter_view

app_name = "website"


urlpatterns = [
    path("about", about_view, name="about"),
    path("contact", contact_us_view, name="contact"),
    path("newsletter", newsletter_view, name="newsletter"),
    path("", index_view, name="index"),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.
# from django_resized import ResizedImageField


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)


class Post(models.Model):
    image = models.ImageField(upload_to="blog/", default="blog/default.jpg")
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    counted_view = models.IntegerField(default=0)    
    login_required = models.BooleanField(default=False)    
    is_published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null=True, blank=True)
    read_duration_minutes = models.DurationField(null=True, blank=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:single", kwargs={"pid": self.id})
    
# adding custom comment model as a substitute for disqus
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField(null=True, blank=True)
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):    
    class Meta:
        model = Comment
        fields = ['post', 'name', 'email', 'subject', 'message']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category
from django.utils import timezone
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.models import User
from .models import Post, Comment
from .forms import CommentForm
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import redirect
# import datetime
# Create your views here.


def blog_view(request, **kwargs):
    # posts = Post.objects.filter(is_published=True)
    posts = Post.objects.filter(published_date__lte=timezone.now(), is_published=True)

    if kwargs.get("cat_name"):
        posts = posts.filter(category__name=kwargs["cat_name"])

    if kwargs.get("author_username"):
        posts = posts.filter(author__username=kwargs["author_username"])

    if kwargs.get("tag_name") != None:
        posts = posts.filter(tags__name__in=[kwargs["tag_name"]])

    # handeling pagination
    posts = Paginator(posts, 2)
    try:
        page_number = request.GET.get("page")
        posts = posts.get_page(page_number)

    except PageNotAnInteger:
        posts.get_page(1)

    except EmptyPage:
        posts.get_page(posts.num_pages)

    # --------------------------------

    context = {"posts": posts}
    return render(request, "blog/blogs.html", context)


def blog_single(request, pid: int):    
    context = {}
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'کامنت شما ثبت شد و بعد از بررسی توسط ادمین منتشر خواهد شد.')
        else:
            messages.add_message(request, messages.ERROR, 'ثبت کامنت شما با خطا مواجه شد.')
                
    posts = Post.objects.filter(
        pk=pid, is_published=True, published_date__lte=timezone.now()
    )
    post = get_object_or_404(posts)
    post.counted_view += 1
    post.save()
    comments = Comment.objects.filter(post=post.id, approved=True).order_by("-created_at")
    form = CommentForm()
    try:
        next_post = (
            Post.objects.filter(
                id__gt=post.id, is_published=True, published_date__lte=timezone.now()
            )
            .order_by("id")
            .first()
        )
        if next_post:
            if not next_post.is_published:
                next_post = None

    except Post.DoesNotExist:
        next_post = None

    try:
        pre_post = (
            Post.objects.filter(
                id__lt=post.id, is_published=True, published_date__lte=timezone.now()
            )
            .order_by("-id")
            .first()
        )

        if pre_post:
            if not pre_post.is_published:
                pre_post = None

    except Post.DoesNotExist:
        pre_post = None

    if post.login_required and not request.user.is_authenticated:
        return redirect(reverse("accounts:login"))

    context = {"post": post, "next_post": next_post, "pre_post": pre_post, 'comments': comments, 'form': form}
    return render(request, "blog/blog-single.html", context)


def single_category_view(request, cat_name):
    posts = Post.objects.filter(is_published=True, published_date__lte=timezone.now())
    posts = posts.filter(category__name=cat_name)
    context = {"posts": posts}

    return render(request, "blog/category-single.html", context)


def categories_view(request):
    posts = Post.objects.filter(is_published=True, published_date__lte=timezone.now())
    categories = Category.objects.all()
    categories_count = {}
    for category in categories:
        counted_categ = posts.filter(category__name=category.name).count()
        if counted_categ:
            categories_count[category.name] = posts.filter(
                category__name=category.name
            ).count()

    context = {"categories": categories_count}
    return render(request, "blog/categories.html", context)


def blog_search(request):
    posts = Post.objects.filter(is_published=True, published_date__lte=timezone.now())
    if request.method == "GET":
        if s := request.GET.get("s"):
            posts = posts.filter(content__contains=s)

    context = {"posts": posts}
    return render(request, "blog/blogs.html", context)


def test_view(request):
    return render(request, "blog/test.html")


def author_view(request):
    posts = Post.objects.filter(is_published=True, published_date__lte=timezone.now())
    authors = User.objects.filter(is_staff=False)
    authors_posts = {}
    for author in authors:
        authors_posts[author.username] = posts.filter(
            author__username=author.username
        ).count()

    context = {"authors": authors_posts}
    return render(request, "blog/author.html", context)


# def author_single_view(request, author_id: int):
#     print('I am called !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
#     posts = Post.objects.filter(is_published=True, published_date__lte=timezone.now())
#     posts = posts.filter(author__id=author_id)
#     author = User.objects.get(id=author_id)
    
#     context = {"posts": posts, "author": author}
#     return render(request, "blog/author-single.html", context)

templates/blog/author.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags%}

{% block navbar %}
<section class="page-header section-sm">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="section-title h2 mb-3">
          <span>نویسنده</span>
        </h1>
        <ul class="list-inline breadcrumb-menu mb-3">
          <li class="list-inline-item"><a href="index.html"><i class="ti ti-home"></i>  <span>خانه</span></a></li>
          <li class="list-inline-item">• &nbsp; <a href="author.html"><span>نویسنده</span></a></li>
        </ul>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block content %}
<section class="section-sm pt-0 mt-3">
  <div class="container">
    <div class="row">
      <div class="col-lg-10 mx-auto">
        <div class="row gx-4 gy-5 gx-md-5 justify-content-center text-center">
          
          {% for author, posts_count in authors.items %}
          <div class="col-md-4 col-sm-6">
            <a class="d-inline-block is-hoverable" href="{% url 'blog:author' author_username=author %}">
              {% comment %} <img class="img-fluid rounded" src="assets/images/author/chris-impey.jpg" alt=" کریس ایپلی" width="150" height="150"> {% endcomment %}
              <h4 class="text-dark mt-4 mb-1"> {{ author }}</h4>
              <p class="mb-0"><span class="fw-bold text-black">{{ posts_count }}</span> پست های منتشرشده </p>
            </a>
          </div>
          {% endfor %}
          
        </div>
      </div>
    </div>
  </div>
</section>

  <!-- blog warpper start -->
  {% latest_posts 6 %}
  <!-- blog warpper end -->

{% endblock %}

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block content %}
<section class="section-sm pb-0">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="mb-5">
          <h3 class="h1 mb-4 post-title">{{ post.title }}</h3>

          <ul class="card-meta list-inline mb-2">
            <li class="list-inline-item mt-2">
              <a href="author-single.html" class="card-meta-author" title="خواندن پست نوشته شده توسط - {{ post.author.get_full_name}}">
                {% comment %} <img class="w-auto" src="assets/images/author/thomas-macaulay.jpg" alt="توماس ماکبی" width="26" height="26"> {% endcomment %}
                 توسط 
                 <span>{{ post.author.get_full_name}}</span>
              </a>
            </li>
            <li class="list-inline-item mt-2">—</li>
            <li class="list-inline-item mt-2">
              <i class="ti ti-clock"></i>
              <span>{{ post.read_duration_minutes}} دقیقه خوانش</span>
            </li>
            <li class="list-inline-item mt-2">—</li>
            <li class="list-inline-item mt-2">
              <i class="ti ti-calendar-event"></i>
              <span>{{ post.published_date | naturaltime }}</span>
            </li>
            <li class="list-inline-item mt-2">—</li>
            <li class="list-inline-item mt-2"> {{ post.counted_view }} بازدید</li>
          </ul>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="mb-5 text-center">
          <img class="w-100 h-auto rounded" src={{ post.image.url }} alt={{ post.title }} width="970" height="auto">
        </div>
      </div>
      <div class="col-lg-2 post-share-block order-1 order-lg-0 mt-5 mt-lg-0">
        <div class="position-sticky" style="top:150px">
          <span class="d-inline-block mb-3 small"> اشتراک گذاری </span>
          <ul class="social-share icon-box">
            <li class="d-inline-block d-lg-block me-2 mb-2" onclick="return tbs_click()"><i class="ti ti-brand-twitter"></i></li>
            <li class="d-inline-block d-lg-block me-2 mb-2" onclick="return fbs_click()"><i class="ti ti-brand-facebook"></i></li>
            <li class="d-inline-block d-lg-block me-2 mb-2" onclick="return ins_click()"><i class="ti ti-brand-linkedin"></i></li>
            <li class="d-inline-block d-lg-block me-2 mb-2" onclick="return red_click()"><i class="ti ti-brand-reddit"></i></li>
            <li class="d-inline-block d-lg-block me-2 mb-2" onclick="return pin_click()"><i class="ti ti-brand-pinterest"></i></li>
          </ul>
        </div>
        <script type="text/javascript">
          var pageLink = window.location.href;
          var pageTitle = String(document.title).replace(/\&/g, '%26');
          function tbs_click(){pageLink = 'https://twitter.com/intent/tweet?text=${pageTitle}&amp;url=${pageLink}';socialWindow(pageLink, 570, 570);}
          function fbs_click(){pageLink = 'https://www.facebook.com/sharer.php?u=${pageLink}&amp;quote=${pageTitle}';socialWindow(pageLink, 570, 570);}
          function ins_click(){pageLink = 'https://www.linkedin.com/sharing/share-offsite/?url=${pageLink}';socialWindow(pageLink, 570, 570);}
          function red_click(){pageLink = 'https://www.reddit.com/submit?url=${pageLink}';socialWindow(pageLink, 570, 570);}
          function pin_click(){pageLink = 'https://www.pinterest.com/pin/create/button/?&amp;text=${pageTitle}&amp;url=${pageLink}&amp;description=${pageTitle}';socialWindow(pageLink, 570, 570);}
          function socialWindow(pageLink, width, height){var left = (screen.width - width) / 2;var top = (screen.height - height) / 2;var params = "menubar=no,toolbar=no,status=no,width=" + width + ",height=" + height + ",top=" + top + ",left=" + left;window.open(pageLink,"",params);}
        </script>
      </div>
      <div class="col-lg-8 post-content-block order-0 order-lg-2">
        <div class="content">
          {{ post.content | safe }}
        </div>

        <ul class="post-meta-tag list-unstyled list-inline mt-5">
          <li class="list-inline-item"> دسته بندی ها: </li>
          {% for category in post.category.all %}
            <li class="list-inline-item"><a href="{% url 'blog:category' cat_name=category.name %}">{{ category.name }}</a></li>
          {% endfor %}
        </ul>
            
        <ul class="post-meta-tag list-unstyled list-inline ">
          <li class="list-inline-item"> برچسب ها: </li>
          {% for tag in post.tags.all %}
            <li class="list-inline-item"><a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a></li>
          {% endfor %}
        </ul>
      
      </div>
    </div>    
  
    {% if pre_post is not None %}      
      <div class="single-post-author">
        <div class="row justify-content-center">
          <div class="col-lg-10">
            <div class="d-block d-md-flex">
              <a href={% url 'blog:single' pid=pre_post.id %}>
                <img class="rounded mr-4" src={{ pre_post.image.url }} alt={{ pre_post.title }} width="120" height="auto">
              </a>

              <a href={% url 'blog:single' pid=pre_post.id %} class="text-dark">
                <div class="ms-0 ms-md-4 ps-0 ps-md-3 mt-4 mt-md-0 mx-md-3">
                  
                  <h5 class="h4 mb-1">پست قبلی</h5>
                  <p>{{ pre_post.title }}</p> 
                </div>
              </a>  
            
            </div>

          </div>
        </div>
      </div>
    {% endif %}

    
    {% if next_post is not None %}
    <div class="single-post-author">
      <div class="row justify-content-center">
        <div class="col-lg-10">
          <div class="d-block d-md-flex">
            <a href={% url 'blog:single' pid=next_post.id %}>
              <img class="rounded mr-4" src={{ next_post.image.url }} alt={{ next_post.title }} width="120" height="auto">
            </a>
            <a href={% url 'blog:single' pid=next_post.id %} class="text-dark">
              <div class="ms-0 ms-md-4 ps-0 ps-md-3 mt-4 mt-md-0 mx-md-3">
                <h5 class="h4 mb-1">پست بعدی</h5>
                <p>{{ next_post.title }}</p>
              </div>
            </a>
          
          </div>
        </div>
      </div>
    </div>

    
    {% endif %}


    {% comment %} 

                                          Handeling Comments using discus

    <div id="disqus_thread"></div>
      <script>
          /**
          *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
          *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
          /*
          var disqus_config = function () {
          this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
          this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
          };
          */
          (function() { // DON'T EDIT BELOW THIS LINE
          var d = document, s = d.createElement('script');
          s.src = 'https://127-0-0-1-8000-zs12fexudn.disqus.com/embed.js';
          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
          })();
      </script>
      <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

  </div>
 {% endcomment %}

{% comment %} Handeling Comments Manually {% endcomment %}
<h2 class="section-title text-center mb-4">نظرات</h2>

{% for comment in comments %}
  <div class="single-post-author">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="d-block d-md-flex">
            <img class="rounded mr-4" src="{% static 'assets/images/author/user.jpg' %}" width="96" height="96">
          </a>          
            <div class="ms-0 ms-md-4 ps-0 ps-md-3 mt-4 mt-md-0 mx-md-3">              
              <h5 class="h4 mb-1">{{ comment.name }}</h5>
              <p>{{ comment.message }}</p> 
              <small>{{ comment.created_at|naturaltime }}</small>
            </div>                  
        </div>
      </div>
    </div>
  </div>
{% empty %}
  <div class="justify-content-center">
    <p> اولین نفری باشید که نظر میدهید! </p>
  </div>
{% endfor %}

<div class="col-lg-5 ms-lg-auto ms-lg-0 ms-auto">
  <h3 class="h3 mb-4">ثبت نظر</h3>

  <form method='Post' action="{% url 'blog:single' pid=post.id %}">
              
    {% csrf_token %}
    
    <input type='hidden' name='post' value={{ post.id }}>

    {% if request.user.is_authenticated %}

    <div class="col-md-12">
      <input type="text" class="form-control" placeholder="نام شما اینجاست" name="name" value={{ request.user.first_name }} hidden required />
    </div>

    <div class="col-md-12">
      <input type="email" class="form-control" placeholder="آدرس ایمیل" name="email" value={{ request.user.email }} hidden required />
    </div>

    {% else %}

    <div class="col-md-12">
      <input type="text" class="form-control" placeholder="نام شما اینجاست" name="name" required />
    </div>

    <div class="col-md-12">
      <input type="email" class="form-control" placeholder="آدرس ایمیل" name="email" required />
    </div>

    {% endif %}

    <div class="col-md-12">
      <input type="text" class="form-control" placeholder="موضوع" name="subject"/>
    </div>

    <div class="col-md-12">
      <textarea class="form-control" placeholder="نظرتون در مورد این مطلب چی بود؟" rows="4" name="message" required></textarea>
    </div>              
    
    {% comment %} <div class="col-md-12">
      {{ form.captcha }}
    </div> {% endcomment %}

    <div class="col-12">
      <button type="submit" class="btn btn-primary" aria-label="ثبت نظر">ارسال <i class="ti ti-brand-telegram me-1"></i></button>
    </div>

  </form>

</div>

</section>
{% endblock %}

templates/blog/blogs.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block navbar %}
  <section class="page-header section-sm">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h1 class="section-title h2 mb-3"><span>همه پست ها</span></h1>
          <ul class="list-inline breadcrumb-menu mb-3">
            <li class="list-inline-item">
              <a href="{% url 'website:index' %}"><i class="ti ti-home"></i> <span>خانه</span></a>
            </li>
            <li class="list-inline-item">
              • &nbsp; <a href="{% url 'blog:index' %}"><span>همه پست ها</span></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row gy-5 gx-4 g-xl-5">
      {% for post in posts %}                            
          {# is even #}
          <div class="col-lg-6">
            <article class="card post-card h-100 border-0 bg-transparent">
              <div class="card-body">
                <a class="d-block" href="{% url 'blog:single' pid=post.id %}" title={{ post.title }}></a>

                <a class="d-block" href="{% url 'blog:single' pid=post.id %}" title={{ post.title }}>
                  <div class="post-image position-relative">
                    <img class="w-100 h-auto rounded" src={{ post.image.url }} alt={{ post.title }} width="970" height="auto">
                  </div>
                </a>

                <ul class="card-meta list-inline mb-3">
                  <li class="list-inline-item mt-2">
                    <i class="ti ti-calendar-event"></i>
                    <span>{{ post.published_date|naturaltime }}</span>
                  </li>
                  <li class="list-inline-item mt-2">—</li>
                  <li class="list-inline-item mt-2">
                    <i class="ti ti-clock"></i>
                    <span>{{ post.read_duration_minutes }} دقیقه خوانش</span>
                  </li>
                </ul>
                <a class="d-block" href="{% url 'blog:single' pid=post.id %}" title={{ post.title }}><h3 class="mb-3 post-title">{{ post.title }}</h3></a>
                <p>{{ post.content | safe | truncatewords:40 | linebreaks}}</p>
              </div>
              <div class="card-footer border-top-0 bg-transparent p-0">
                <ul class="card-meta list-inline">
                  <li class="list-inline-item mt-2">
                    <a href="{% url 'blog:author' author_username=post.author.username %}" class="card-meta-author">
                      توسط 
                      <span>{{ post.author.get_full_name }}</span>
                    </a>
                  </li>
                  </li>
                  <li class="list-inline-item mt-2">•</li>
                  <li class="list-inline-item mt-2"> {{ post.counted_view }} بازدید</li>
                  <li class="list-inline-item mt-2">•</li>
                  <li class="list-inline-item mt-2">
                    <ul class="card-meta-tag list-inline">
                      {% for category in post.category.all %}
                        <li class="list-inline-item small"><a href="{% url 'blog:category' cat_name=category.name %}">{{ category.name }}</a></li>
                      {% endfor %}
                    </ul>
                  </li>
                  
                </ul>
              </div>

            </article>
          </div>
        
      {% endfor %}

      <div class="col-12">
        <!-- pagination -->
        <nav class="text-center mt-5">
          <ul class="pagination justify-content-center border border-white rounded d-inline-flex">

            {% if posts.number != 1 %}
            <li class="page-item"><a class="page-link rounded w-auto px-4" href="?page=1" aria-label="Pagination Arrow">اولین</a></li>
            {% endif%}

            {% if posts.has_previous %}
              <li class="page-item"><a class="page-link rounded w-auto px-4" href="?page={{ posts.previous_page_number }}" aria-label="Pagination Arrow">قبلی</a></li>
            {% endif%}
            
            {% for i in posts.paginator.page_range%}              
              <li class="page-item {% if i == posts.number %} active {% endif %}" >
                <a href="?page={{ i }}" class="page-link rounded">{{ i }}</a>
              </li>
            {% endfor%}

            {% if posts.has_next %}
              <li class="page-item"><a class="page-link rounded w-auto px-4" href="?page={{ posts.next_page_number }}" aria-label="Pagination Arrow">بعدی</a></li>
            {% endif%}

            {% if posts.number != posts.paginator.num_pages %}
              <li class="page-item"><a class="page-link rounded w-auto px-4" href="?page={{ posts.paginator.num_pages }}" aria-label="Pagination Arrow">آخرین</a></li>
            {% endif%}

          </ul>
        </nav>
        
      </div>

    </div>
  </div>
{% endblock %}

templates/blog/categories.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
  <section class="page-header section-sm">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h1 class="section-title h2 mb-3"><span>دسته‌بندی‌ها</span></h1>
          <ul class="list-inline breadcrumb-menu mb-3">
            <li class="list-inline-item">
              <a href="{% url 'website:index' %}"><i class="ti ti-home"></i> <span>خانه</span></a>
            </li>
            <li class="list-inline-item">
              • &nbsp; <a href="{% url 'blog:categories' %}"><span>دسته‌بندی‌ها</span></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row g-4 justify-content-center text-center">
      {% for category, count in categories.items %}
        <div class="col-lg-4 col-sm-6">
          <a class="p-4 rounded bg-white d-block is-hoverable" href="{% url 'blog:category' cat_name=category %}">
            <span class="h3"><i class="ti ti-color-swatch mb-2"></i></span>
            <span class="h4 mt-2 mb-3 d-block">{{ category }}</span>
            {{ count }} پست
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/blog/test.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>



      

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>