accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    # path('reset-password/', views.reset_password_view, name='reset-password'),
    # path('reset-password/', views.reset_password_view, name='reset password'),

    # profile
    # password_reset    
]

blog/urls.py
from django.urls import path
from .feeds import LatestEntriesFeed
from .views import (
    blog_view,
    blog_single,
    test_view,
    categories_view,
    blog_search,
    author_view,
)

app_name = "blog"

urlpatterns = [
    path("", blog_view, name="index"),
    path("<int:pid>", blog_single, name="single"),
    path("category/<str:cat_name>", blog_view, name="category"),
    path("categories", categories_view, name="categories"),
    path("tag/<str:tag_name>", blog_view, name="tag"),
    path("author/<str:author_username>", blog_view, name="author"),
    path("search/", blog_search, name="search"),
    path("author/", author_view, name="author"),
    path("test", test_view, name="test"),
    path("rss/feed", LatestEntriesFeed(), name="rss"),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

# development time imports
import debug_toolbar
from django.urls import path  
from website.views import maintenance 
# ------------------------

from django.conf import settings
from django.urls import re_path
# from django.conf.urls import handler404

handler404 = 'website.views.custom_404'

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}


urlpatterns = [
    path('maintenance/', maintenance, name='maintenance'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('website.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('robots.txt', include('robots.urls')),
    path("__debug__/", include(debug_toolbar.urls)),
    path('summer_note/', include('django_summernote.urls')),
    path(r'captcha/', include('captcha.urls')), 
    path('accounts/', include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from .views import about_view, contact_us_view, index_view, newsletter_view

app_name = "website"


urlpatterns = [
    path("about", about_view, name="about"),
    path("contact", contact_us_view, name="contact"),
    path("newsletter", newsletter_view, name="newsletter"),
    path("", index_view, name="index"),

]

templates/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en-US">

 
<!-- => ALDev @ market.radib.com <= about.html => Uploaded at Radib File Markket <=  [XR&CO'2014], Sat, 29 Jan 2022 11:37:24 GMT -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8" /> 
<head>
  <meta charset="utf-8">
  <title>کورنو - بلاگ تکنولوژی </title>

  <meta name="author" content="Platol">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5">
  <meta name="description" content="Minimal Blog HTML Template">

  <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" type="image/x-icon">

  <!-- CSS Plugins -->
  <link rel="preconnect" href="https://fonts.googleapis.com/">
  <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Crete+Round&amp;family=Work+Sans:wght@500;600&amp;display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css'%}">
  <link rel="stylesheet" href="{% static 'plugins/tabler-icons/tabler-icons.min.css'%}">

  <!-- Main Stylesheet -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css'%}">
</head>
<body>

  {% include 'message.html' %}

<div class="header-height-fix"></div>
<header class="header-nav">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg navbar-light p-0">
          <!-- logo -->
          <a class="navbar-brand font-weight-bold mb-0" href="{% url 'website:index' %}" title="Qurno">
            <img class="img-fluid" width="110" height="35" src="{% static 'assets/images/logo.png' %}" alt="Qurno">
          </a>

          <button class="search-toggle d-inline-block d-lg-none me-auto ms-1 ms-sm-3" data-toggle="search" aria-label="Search Toggle">
            <span>جستجو</span>
            <svg width="22" height="22" stroke-width="1.5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M15.5 15.5L19 19" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/><path d="M5 11C5 14.3137 7.68629 17 11 17C12.6597 17 14.1621 16.3261 15.2483 15.237C16.3308 14.1517 17 12.654 17 11C17 7.68629 14.3137 5 11 5C7.68629 5 5 7.68629 5 11Z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/></svg>
          </button>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navHeader" aria-controls="navHeader" aria-expanded="false" aria-label="Toggle navigation">
            <i class="ti ti-menu-2 d-inline"></i>
            <i class="ti ti-x d-none"></i>
          </button>

          <div class="collapse navbar-collapse" id="navHeader">
            <ul class="navbar-nav mx-auto">
              <li class="nav-item @@home">
                <a class="nav-link" href="{% url 'website:index' %}">خانه</a>
              </li>
              <li class="nav-item @@about">
                <a class="nav-link" href="{% url 'website:about' %}">درباره ما</a>
              </li>              
              <li class="nav-item @@archive">
                <a class="nav-link" href="{% url 'blog:index' %}">بلاگ</a>
              </li>
              <li class="nav-item @@contact">
                <a class="nav-link" href="{% url 'website:contact' %}">ارتباط با ما</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">صفحات</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'blog:author' %}">نویسنده ها</a></li>
                  {% comment %} <li><a class="dropdown-item" href="#">برچسب‌ها</a></li> {% endcomment %}
                  <li><a class="dropdown-item" href="{% url 'blog:categories' %}">دسته‌بندی‌ها</a></li>                  
                </ul>
              </li>
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#"><b>{{request.user.username}}</b> خوش آمدید </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">خروج</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">ورود</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">ثبت نام</a>
              </li>
              {% endif %}
            </ul>
            
            <div class="navbar-right d-none d-lg-inline-block">
              <ul class="social-links list-unstyled list-inline">
                <li class="list-inline-item ms-4 d-none d-lg-inline-block">
                  <button class="search-toggle" data-toggle="search" aria-label="Search Toggle">
                    <span>جستجو</span>
                    <svg width="22" height="22" stroke-width="1.5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M15.5 15.5L19 19" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/><path d="M5 11C5 14.3137 7.68629 17 11 17C12.6597 17 14.1621 16.3261 15.2483 15.237C16.3308 14.1517 17 12.654 17 11C17 7.68629 14.3137 5 11 5C7.68629 5 5 7.68629 5 11Z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/></svg>
                  </button>
                </li>
              </ul>
            </div>

          </div>
        </nav>
      </div>
    </div>
  </div>
</header>

<!-- Search bar -->
<div class="search-block">
  
  <div data-toggle="search-close">
    <span class="ti ti-x text-primary"></span>
  </div>
  <form method="get" action="{% url 'blog:search' %}">
    <input type="text" id="js-search-input" name="s" placeholder="تایپ کنید دنبال چه هستید..." aria-label="search-query">    
  </form>
  
  <div class="mt-4 card-meta">
    <p class="h4 mb-3">دیدن پست ها بر اساس برچسب</p>
    <ul class="card-meta-tag list-inline">
      {% comment %} {% for  in  %} {% endcomment %}
      <li class="list-inline-item me-1 mb-2">
        <a class="small" href="tag-single.html">زندگی</a>
      </li>
      {% comment %} {% endfor %} {% endcomment %}
    </ul>
  </div>

  {% search_by_categories %}

</div>
<!-- End Search bar -->

{% block navbar %}
{% endblock navbar %}

{% block content %}
{% endblock content %}


{% comment %} {% block default_messages %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% endblock default_messages %} {% endcomment %}

<!-- start of footer -->
<footer>
  <div class="container">
    <div class="section">
      <div class="row justify-content-center align-items-center">
        <div class="col-xl-6 col-lg-8 col-md-10">
          <!-- newsletter block -->
          <div class="newsletter-block">
            <h2 class="section-title text-center mb-4">آخرین پست ها را در صندوق ایمیل خود داشته باشید</h2>
            <form action="{% url 'website:newsletter' %}" method="post" novalidate>
              {% csrf_token %}
              <div class="input-group flex-column flex-sm-row flex-nowrap flex-sm-nowrap">
                <input type="email" name="email" class="form-control required email w-auto text-center text-sm-start" placeholder="آدرس ایمیل شما" aria-label="Subscription" required>
                <div class="input-group-append d-flex d-sm-inline-block mt-2 mt-sm-0 ms-0 w-auto">
                  <button type="submit" name="subscribe" id="mc-embedded-subscribe" class="input-group-text w-100 justify-content-center" aria-label="Subscription Button"><i class="ti ti-user-plus ms-2"></i>ملحق شوید</button>
                </div>
              </div>
            </form>
          </div>
          <!-- newsletter block -->
        </div>
      </div>
    </div>
    <div class="pb-5">
      <div class="row g-2 g-lg-4 align-items-center">
        <div class="col-lg-6 text-center text-lg-end">
          <p class="mb-0 copyright-text content">&copy; 1400 کورنو . همه حقوق محفوظ است .</p>
        </div>
        
      </div>
    </div>
  </div>
</footer>
<!-- end of footer -->

<!-- JS Plugins -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/lightense/lightense.min.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'assets/js/script.js' %}"></script>


{% comment %} Messages JS {% endcomment %}
{% if messages %}
  <script>
      {% for message in messages %}
          $(document).ready(function () {
              $('.toast').toast('show');
          });
      {% endfor %}
  </script>
{% endif %}

</body>

</html>

templates/message.html
<div class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 1050">
  {% for message in messages %}
  <div class="toast notification bg-" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000">
    <div class="toast-body text-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}" style="text-align: left;">{{message|safe}}</div>
  </div>
  {% endfor %}
</div>